#!/bin/bash

DATE=$(date +"%Y-%m-%d_%H:%M%S")
mkdir -p ~/autopics
avconv -f video4linux2 -s 2000x2000 -i /dev/video0 -ss 0:0:10 -frames 1 ~/autopics/$DATE.jpg

# install avconv: sudo apt-get install libav-tools
